# payment查询
GET http://localhost:8001/payment/1
Accept: application/json;charset=utf-8

###
# 创建
POST http://localhost:8001/payment/create
Accept: application/json;charset=utf-8
Content-Type: application/json

{
"serial":"hhe"
}
###
# payment hystrix test
GET http://localhost:8006/payment/error/hahah
Accept: application/json;charset=utf-8


###
GET http://localhost:8001/payment/timeout/1
Accept: application/json;charset=utf-8

###
# order

GET http://localhost/order/consumer/payment/1
Accept: application/json;charset=utf-8
Accept-Language:fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5

###
POST http://localhost/order/consumer/payment/create
Accept: application/json;charset=utf-8
Content-Type: application/json

{
"serial":"consumer"
}

###
GET http://localhost/order/consumer/payment/timeout/1
Accept: application/json;charset=utf-8
Accept-Language:fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5

###
# order Zk test
GET http://localhost/order/zk
Accept: application/json;charset=utf-8
Accept-Language:fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5

###
# order Consul registry test
GET http://localhost/order/consul
Accept: application/json;charset=utf-8
Accept-Language:fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5

###
# order ribbon customer loadbalancer rule
GET http://localhost/order/useMyLoadBalancer/payment/1
Accept: application/json;charset=utf-8
Accept-Language:fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5

###
#order hystrix test
GET http://localhost/order/consumer/payment/errorTimeout/haha
Accept: application/json;charset=utf-8
Accept-Language:fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5

###
# test circuitBreaker
GET http://localhost:8002/payment/circuitBreak?index=1
Accept: application/json;charset=utf-8
Accept-Language:fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5

###
# test Gateway LoadBalancer
GET http://localhost:9527/payment/lb
Accept: application/json;charset=utf-8
Accept-Language:fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5

###
# test Gateway GlobalFilter
GET http://localhost:9527/payment/lb?token=access
Accept: application/json;charset=utf-8
Accept-Language:fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5

###
# test gateway circuitBreaker
GET http://localhost:9527/payment/circuitBreak?index=1&token=access
Accept: application/json;charset=utf-8
Accept-Language:fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5

