server:
  port: 7001

spring:
  application:
    name: cloud-server-eureka-7001


eureka:
  instance:
    # eureka 服务端实例名称
    appname: eureka7001.com
    prefer-ip-address: true
  client:
    # 是否向注册中心注册自己 false表示不注册
    register-with-eureka: false
    # false 表示自己端就是注册中心,职责是维护服务实例,不需要去检索服务
    fetch-registry: false
    service-url:
    #      defaultZone: http://eureka7002:7002/eureka/
      defaultZone: http://${eureka.instance.appname}:${server.port}/eureka
  server:
    # 关闭自我保护机制
    enable-self-preservation: false
    # 移除服务的时间间隔
    eviction-interval-timer-in-ms: 2000


