server:
  port: 80

spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1


# Logger Config
logging:
  level:
    com.ycorn.payment.dao: debug

# 暴露监控
management:
  endpoints:
    web:
      exposure:
        include: "*"



