server:
  port: 80
spring:
 datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-learn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
 application:
   name: cloud-service-order

eureka:
#  instance:
#    # eureka 服务端实例名称
#    appname: localhost
  client:
    #  true 将自己也注册到eureka中成为一个服务实例
    register-with-eureka: true
    # true 需要从eureka中获取服务实例
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/