server:
  port: 80
spring:
  application:
    name: cloud-service-order-hystrix

eureka:
  instance:
    # eureka 服务端实例名称 会覆盖Spring.Application.name 展示在eureka console中
    #    appname: order
    prefer-ip-address: true
    #   Eureka 	Status中展示的名称 替代主机名
    instance-id: order
  client:
    #  true 将自己也注册到eureka中成为一个服务实例
    register-with-eureka: true
    # true 需要从eureka中获取服务实例
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

# 配置fegin 调用日志查看
logging:
  level:
    com.ycorn.service.PaymentServiceFeignClient: debug

ribbon:
  ReadTimeout: 6000 #处理请求的超时时间，默认为1秒
  ConnectTimeout: 1000
#
feign:
  hystrix:
    enabled: true
#
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #是否开启超时熔断
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000 #断路器超时时间，默认1000ms