server:
  port: 7002

spring:
  application:
    name: cloud-server-eureka-7002


eureka:
  instance:
    # eureka 服务端实例名称 不写默认为${spring.application.name} 大写
    appname: eureka7002.com
  client:
    # 是否向注册中心注册自己 false表示不注册
    register-with-eureka: false
    # false 表示自己端就是注册中心,职责是维护服务实例,不需要去检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001:7001/eureka/


