server:
  port: 80

spring:
  application:
    name: cloud-service-order-ribbon

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka