# payment查询
GET http://localhost:8001/payment/1
Accept: application/json;charset=utf-8

###
# 创建
POST http://localhost:8001/payment/create
Accept: application/json;charset=utf-8
Content-Type: application/json

{
"serial":"hhe"
}

###
# order

GET http://localhost/order/consumer/payment/1
Accept: application/json;charset=utf-8
Accept-Language:fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5

###
POST http://localhost/order/consumer/payment/create
Accept: application/json;charset=utf-8
Content-Type: application/json

{
"serial":"consumer"
}

###